### ISSUE TITLE
The given key was not present in the dictionary.

### ISSUE THREAD

**Issue by jholovacs** [tmenier/AsyncPoco#34]
I have a table defined as such:

```
create table Transient.BulkEditedCreative (
	BulkEditedCreativeId int not null identity constraint PK_BulkEditedCreative primary key,
	CampaignId int not null constraint FK_BulkEditedCreative_CampaignId references DSP.Campaign(CampaignId),
	SessionId uniqueidentifier not null,
	CreativeId int null constraint FK_BulkEditedCreative_CreativeId references DSP.Creative(CreativeId),
	CreativeName varchar(200) null,
	DestinationUrl varchar(1024) null,
	ShortText nvarchar(60) null,
	LongText nvarchar(150) null,
	SponsoredBy nvarchar(30) null,
	ImageNames varchar(max) null,
	ViewTags varchar(max) null,
	[Status] varchar(30) not null,
	OperationType varchar(30) not null,
	ErrorMessage varchar(max) null,
	CreatedDate datetime not null,
	ModifiedBy varchar(100) not null
	);
```

This corresponds with the POCO defined as such:
```
public class BulkEditedCreative
{
	public int BulkEditedCreativeId { get; set; }
	public int CampaignId { get; set; }
	public Guid SessionId { get; set; }
	public int? CreativeId { get; set; }
	public string CreativeName { get; set; }
	public string DestinationUrl { get; set; }
	public string ShortText { get; set; }
	public string LongText { get; set; }
	public string SponsoredBy { get; set; }

	/// <summary>
	///     JSON-encoded list of image names
	/// </summary>
	public string ImageNames { get; set; }

	/// <summary>
	///     JSON-encoded list of creative impression pixels
	/// </summary>
	public string ViewTags { get; set; }
	public BulkEditStatuses Status { get; set; }
	public OperationTypes OperationType { get; set; }

	/// <summary>
	///     JSON-encoded <see cref="BulkOperationValidationMessage" /> object.
	/// </summary>
	public string ErrorMessage { get; set; }

	public DateTime CreatedDate { get; set; }
	public string ModifiedBy { get; set; }
}

public enum BulkEditStatuses
{
	Undefined = 0,
	Unchanged,
	Accepted,
	Error
}

public enum OperationTypes
{
	Undefined = 0,
	Insert,
	Update,
	Delete,
	Merge,
	NoChange
}

```

This code generates the mentioned error (sessionId, operationId is a Guid):

```
const string query = "select * from [Transient].[BulkEditedCreative] with (nolock) where SessionId = @sessionId;";
using (var db = _databaseFactory.GetBidtellectDb())
{
	var result = await db.FetchAsync<BulkEditedCreative>(query, new {sessionId = operationId});
	return GenerateBulkCreativeEditSpreadsheet(result);
}
```

Exception text is:  

> System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.

Stack Trace is:

>   at System.ThrowHelper.ThrowKeyNotFoundException()
>    at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
>    at petapoco_factory_0(IDataReader )
>    at AsyncPoco.Database.<QueryAsync>d__51`1.MoveNext() in C:\Aldenteware\AsyncPoco\code\AsyncPoco\Database.cs:line 963
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at AsyncPoco.Database.<FetchAsync>d__37`1.MoveNext() in C:\Aldenteware\AsyncPoco\code\AsyncPoco\Database.cs:line 625
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
>    at MyProject.CreativeBulkOperationService.<GenerateBulkCreativeEditSpreadsheet>d__6.MoveNext() in D:\MyProject\CreativeBulkOperationService.cs:line 350

The problem definitely appears to be in the AsyncPoco project, as the same query string works with the following code:

```
using (var conn = new SqlConnection(ConfigurationManager.ConnectionStrings["MyProjectContext"].ConnectionString))
{
	await conn.OpenAsync();
	using (var comm = new SqlCommand(query, conn))
	{
		comm.Parameters.Add("@sessionId", SqlDbType.UniqueIdentifier).Value = operationId;
		using (var reader = await comm.ExecuteReaderAsync())
		{
			var bulkEditedCreativeIdColumn = reader.GetOrdinal("BulkEditedCreativeId");
			var campaignIdColumn = reader.GetOrdinal("CampaignId");
			var sessionIdColumn = reader.GetOrdinal("SessionId");
			var creativeIdColumn = reader.GetOrdinal("CreativeId");
			var creativeNameColumn = reader.GetOrdinal("CreativeName");
			var destinationUrlColumn = reader.GetOrdinal("DestinationUrl");
			var shortTextColumn = reader.GetOrdinal("ShortText");
			var longTextColumn = reader.GetOrdinal("LongText");
			var sponsoredByColumn = reader.GetOrdinal("SponsoredBy");
			var imageNamesColumn = reader.GetOrdinal("ImageNames");
			var viewTagsColumn = reader.GetOrdinal("ViewTags");
			var statusColumn = reader.GetOrdinal("Status");
			var operationTypeColumn = reader.GetOrdinal("OperationType");
			var errorMessageColumn = reader.GetOrdinal("ErrorMessage");
			var createdDateColumn = reader.GetOrdinal("CreatedDate");
			var modifiedByColumn = reader.GetOrdinal("ModifiedBy");

			var result = new List<BulkEditedCreative>();

			while (reader.Read())
			{
				var item = new BulkEditedCreative
				{
					BulkEditedCreativeId = reader.Get<int>(bulkEditedCreativeIdColumn),
					CreativeId = reader.Get<int?>(creativeIdColumn),
					CreativeName = reader.Get<string>(creativeNameColumn),
					CampaignId = reader.Get<int>(campaignIdColumn),
					SessionId = reader.Get<Guid>(sessionIdColumn),
					DestinationUrl = reader.Get<string>(destinationUrlColumn),
					ShortText = reader.Get<string>(shortTextColumn),
					LongText = reader.Get<string>(longTextColumn),
					SponsoredBy = reader.Get<string>(sponsoredByColumn),
					ImageNames = reader.Get<string>(imageNamesColumn),
					ViewTags = reader.Get<string>(viewTagsColumn),
					ErrorMessage = reader.Get<string>(errorMessageColumn),
					CreatedDate = reader.Get<DateTime>(createdDateColumn),
					ModifiedBy = reader.Get<string>(modifiedByColumn)
				};

				BulkEditStatuses status;
				if (Enum.TryParse(reader.Get<string>(statusColumn), out status))
				{
					item.Status = status;
				}

				OperationTypes operationType;
				if (Enum.TryParse(reader.Get<string>(operationTypeColumn), out operationType))
				{
					item.OperationType = operationType;
				}

				result.Add(item);
			}
			return GenerateBulkCreativeEditSpreadsheet(result);
		}
	}
}
```
I am currently using the Nuget version 1.2.0.  Any suggestions?  I don't want to use ADO.NET if I don't have to.

**Comment by jholovacs** [comment]
It looks like what's happening is that AsyncPoco, when storing enum values to a varchar column, are saving the string of the numeric value of the enum, i.e. in the example above, `OperationTypes.Insert` would have the value 1 associated, but instead of saving "Insert" into the db, it saves "1", and the EnumMapper can't figure that out.

**Comment by tmenier** [comment]
Sorry for the delay. Could you provide a unit test in your PR to demonstrate this? (i.e. fails before the fix, passes after)

**Comment by jholovacs** [comment]
I have added some unit tests (and some functionality for writing enums as strings as desired)

**Comment by tmenier** [comment]
Sorry, I can't accept the PR. There are 115 failing tests.

Also, my memory is sketchy on this but I'm almost certain support for string-enum mapping already exists. [This test](https://github.com/tmenier/AsyncPoco/blob/master/AsyncPoco.Tests/Misc.cs#L38) seems to indicate support at the mapper level, although I don't see any tests that take it all the way to actual database calls. In that regard I like where you're going with your tests. If you don't mind, could you do this:

1. Create a new fork
2. Work in _just_ your updates to the test project (from your PR), minus calls to `TreatEnumsAsString = true`.

At that point we should be at a state of 2 failing tests to work with. Then I can jump in if needed and see if we're just missing a configuration, like an attribute or something. Or it's possible there's a bug. But since it appears that string-enum support already existed at least in theory, I think we should be able to get it to work without adding a `TreatEnumsAsString` bit.

As a side note, your PR included a LOT of non-behavioral changes, like breaking one-liners into 2, presumably to add breakpoints. It might sound picky but it helps me out a lot to undo those things before you push so that the important changes don't get too lost in the weeds when I review the PR. Thanks!

**Comment by jholovacs** [comment]
Which tests were failing?  For me, tests for all db systems I had installed
on my machine passed.

Petapoco has enum-string support, but I assumed this was forked before it
was implemented.

I'd like to make the case for breaking the statements up; as you said, it's
for adding breakpoints and much easier to debug, and should compile the
same.  I could do that on a different fork, unless you're aesthetically
opposed to it.

**Comment by tmenier** [comment]
For me there 29 failures for each dbms under DatabaseTests, and one under EnumMapper. On closer inspection the DatabaseTest failures mostly looked like this or very similar:

```
System.Data.SqlClient.SqlException : Conversion failed when converting the nvarchar value 'Yes' to data type int.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryHasMoreRows(Boolean& moreRows)
   at System.Data.SqlClient.SqlDataReader.TryReadInternal(Boolean setTimeout, Boolean& more)
   at System.Data.SqlClient.SqlDataReader.<>c__DisplayClass189_0.<ReadAsync>b__0(Task t)
   at System.Data.SqlClient.SqlDataReader.InvokeRetryable[T](Func`2 moreFunc, TaskCompletionSource`1 source, IDisposable objectToDispose)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at AsyncPoco.Database.<ExecuteScalarHelperAsync>d__158.MoveNext() in C:\Aldenteware\AsyncPoco\repo-issue34\AsyncPoco\Database.cs:line 2363
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at AsyncPoco.Database.<InsertAsync>d__67.MoveNext() in C:\Aldenteware\AsyncPoco\repo-issue34\AsyncPoco\Database.cs:line 1348
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at AsyncPoco.Tests.DatabaseTests.<InsertRecordsAsync>d__12.MoveNext() in C:\Aldenteware\AsyncPoco\repo-issue34\AsyncPoco.Tests\DatabaseTests.cs:line 134
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at AsyncPoco.Tests.DatabaseTests.<Transaction_complete>d__28.MoveNext() in C:\Aldenteware\AsyncPoco\repo-issue34\AsyncPoco.Tests\DatabaseTests.cs:line 564
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at NUnit.Framework.Internal.AsyncInvocationRegion.AsyncTaskInvocationRegion.WaitForPendingOperationsToComplete(Object invocationResult)
   at NUnit.Framework.Internal.Commands.TestMethodCommand.RunAsyncTestMethod(TestExecutionContext context)
```
