### ISSUE TITLE
Missing expression when using UpdateAsync(poco)

### ISSUE THREAD

**Issue by jonast92** [tmenier/AsyncPoco#38]
I have a defined poco that's working like a charm with Inserts and Selects. 

The problem I'm encountering is that when calling UpdateAsync only by using the poco as the argument I run into a problem where it seems as if AsyncPoco is not able to construct the required sql statement within, assuming by the OracleException that's thrown.

I call the UpdateAsync method with a defined poco as such:

```
using (var database = new AsyncPoco.Database(conn))
{
    await database.UpdateAsync(poco);
    // ...
}
```
Poco is defined as such:

```
    [TableName("SCHEMA.SCHEMA_TABLE")]
    [PrimaryKey("PK_COL", sequenceName = "SCHEMA.SCHEMA_TABLE_SEQ")]
    public class Poco
    {
        [Column("PK_COL")]
        public long Id { get; set; }

        [Column("ID_USER")]
        [Required(ErrorMessage = "UserId is required")]
        public long UserId { get; set; }
    }
```
My poco has more properties but It's irrelevant.

I receive the following error when calling the method using the poco:

> Oracle.ManagedDataAccess.Client.OracleException: ORA-00936: missing expression

### The stacktrace

```
Result StackTrace:	
at OracleInternal.ServiceObjects.OracleCommandImpl.VerifyExecution(OracleConnectionImpl connectionImpl, Int32& cursorId, Boolean bThrowArrayBindRelatedErrors, OracleException& exceptionForArrayBindDML, Boolean& hasMoreRowsInDB, Boolean bFirstIterationDone)
   at OracleInternal.ServiceObjects.OracleCommandImpl.VerifyExecution(OracleConnectionImpl connectionImpl, Int32& cursorId, Boolean bThrowArrayBindRelatedErrors, OracleException& exceptionForArrayBindDML, Boolean bFirstIterationDone)
   at OracleInternal.ServiceObjects.OracleCommandImpl.ExecuteNonQuery(String commandText, OracleParameterCollection paramColl, CommandType commandType, OracleConnectionImpl connectionImpl, Int32 longFetchSize, Int64 clientInitialLOBFS, OracleDependencyImpl orclDependencyImpl, Int64[]& scnFromExecution, OracleParameterCollection& bindByPositionParamColl, Boolean& bBindParamPresent, OracleException& exceptionForArrayBindDML, Boolean isFromEF)
   at Oracle.ManagedDataAccess.Client.OracleCommand.ExecuteNonQuery()
   at System.Data.Common.DbCommand.ExecuteNonQueryAsync(CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at AsyncPoco.Database.<UpdateAsync>d__70.MoveNext() in C:\Aldenteware\AsyncPoco\code\AsyncPoco\Database.cs:line 1471
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at <my resource>
```

My current workaround consists of creating a utility method that takes the poco and I construct a new Sql class and use that to perform the update but I'd rather not be reliant on custom utility methods to use  AsyncPoco.

**Comment by tmenier** [comment]
Are you willing to help with a fix? I don't have Oracle installed locally so I depend on community help for anything Oracle-specific. I would start by running your app in debug mode, and when the exception is hit, AsyncPoco should output the SQL statement to the debug console, which should help us figure out what Oracle doesn't like about it.

**Comment by jonast92** [comment]
I took a look at the query AsyncPoco is creating and it's on the following form: UPDATE TABLENAME SET "COL1" = :0, "COL2" = :1, "COL3" = :2, "COL4" = :3 WHERE "PRIMARYKEY" = @4

Apparently the query AsyncPoco is constructing is using the @ identifier, according to the official [documentation](https://msdn.microsoft.com/en-us/library/system.data.oracleclient.oraclecommand.parameters.aspx) this will not work, as the primary key value has to be referenced by a : identifier.

I forked the repo, changed it locally and now it works like a charm. I've made a pull request with the change. Hopefully this does not cause problems with others DBRMs. Please review and test it with your DBRM of choice.

If this query string format is not acceptable for other DBRMS than Oracle I'm sure you can find a way?

**Comment by tmenier** [comment]
Fixed & released to NuGet.

**Comment by tmenier** [comment]
@jonast92 I'm actively working on AsyncPoco 2.0, which will primarily be about .NET Core support. Looking for feedback from some active users on another decision: I'm considering dropping the single drop-in file (AsyncPoco.cs) AND the T4 templates. Do you use either, or do you just pull down the NuGet package and go?
